FROM openjdk:17-jdk-alpine
# Create a directory for the app
WORKDIR /app
# Copy the app to the container
COPY . .

# install dependencies
RUN ./mvnw clean package -DskipTests

# run the app
CMD ["java", "-jar", "target/docker-demo-0.0.1-SNAPSHOT.jar"]
